// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0B4O0BocPLUBSn10-gis8VAozWysDYVI',
    appId: '1:205934383175:android:c6cea6193940bc5a752162',
    messagingSenderId: '205934383175',
    projectId: 'vayujal-db-for-customer-device',
    storageBucket: 'vayujal-db-for-customer-device.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiEWFFM2NaXIPHORpLaBebYlHRb73f4b8',
    appId: '1:205934383175:ios:02bcc6913e6c53ab752162',
    messagingSenderId: '205934383175',
    projectId: 'vayujal-db-for-customer-device',
    storageBucket: 'vayujal-db-for-customer-device.firebasestorage.app',
    iosBundleId: 'com.example.vayujal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiEWFFM2NaXIPHORpLaBebYlHRb73f4b8',
    appId: '1:205934383175:ios:02bcc6913e6c53ab752162',
    messagingSenderId: '205934383175',
    projectId: 'vayujal-db-for-customer-device',
    storageBucket: 'vayujal-db-for-customer-device.firebasestorage.app',
    iosBundleId: 'com.example.vayujal',
  );
}
